// stubs/inertia-vue-ts/resources/js/Components/DropdownLink.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3';

defineProps<{
    href: string;
}>();
</script>

<template>
    <Link
        :href="href"
        class="block w-full px-4 py-2 text-left text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out"
    >
        <slot />
    </Link>
</template>

// stubs/inertia-svelte/resources/js/Components/DropdownLink.svelte
<script>
    import { Link } from '@inertiajs/svelte';

    export let href = undefined;
    export let method = undefined;
    export let as = undefined;
</script>

<Link
    {href}
    {method}
    {as}
    class="block w-full px-4 py-2 text-left text-sm leading-5 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus:bg-gray-100 dark:focus:bg-gray-800 transition duration-150 ease-in-out"
>
    <slot />
</Link>
