// stubs/inertia-react/resources/js/Components/TextInput.js
import React, { useEffect, useRef } from "react";

export default function TextInput({ label, type = 'text', name, value, className, autoComplete, required, isFocused, handleChange }) {

    const input = useRef();

    useEffect(() => {
        if (isFocused) {
            input.current.focus();
        }
    }, []);

    return (
        <div className="flex flex-col items-start">
            <input
                type={type}
                name={name}
                value={value}
                className={`border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm ` + className}
                ref={input}
                autoComplete={autoComplete}
                required={required}
                onChange={(e) => handleChange(e)}
            />
        </div>
    );
}

// stubs/inertia-svelte/resources/js/Components/TextInput.svelte
<script>
    export let value = undefined;
    export let name = undefined;
    export let id = name;
    export let autoComplete = undefined;
    export let required = undefined;
    export let type = "text";

    let input;

    export const focus = () => input.focus();
    export const select = () => input.select();

    $: props = {
        ...$$restProps,
    };

    export const update = (event) => {
        value = event.target.value;
    };
</script>

<div class="flex flex-col items-start">
    <input
        {type}
        {name}
        {value}
        {id}
        class={`border-gray-300 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300 focus:border-indigo-500 dark:focus:border-indigo-600 focus:ring-indigo-500 dark:focus:ring-indigo-600 rounded-md shadow-sm ` +
            $$restProps.class}
        {autoComplete}
        {required}
        bind:this={input}
        on:input={update}
    />
</div>
