// stubs/inertia-svelte/resources/js/Components/InputLabel.svelte
<script>
    export let value = undefined;
    let forInput;
    export { forInput as for };
</script>

<label for={forInput} class="block text-sm font-medium text-gray-700 dark:text-gray-300">
    {#if value}
        <span>{value}</span>
    {:else}
        <span><slot /></span>
    {/if}
</label>

// stubs/inertia-react/resources/js/Components/InputLabel.jsx
import React from 'react';

export default function InputLabel({ forInput, value, className, children }) {
    return (
        <label htmlFor={forInput} className={`block font-medium text-sm text-gray-700 dark:text-gray-300 ` + className}>
            {value ? value : children}
        </label>
    );
}
