// stubs/inertia-react/resources/js/Components/UI/ResponsiveNavLink.js
import { InertiaLink } from "@inertiajs/inertia-react";
import React from "react";

export default function ResponsiveNavLink({ active, href, children, method }) {
    return (
        <InertiaLink
            method={method}
            as="button"
            className={
                `w-full flex items-start pl-3 pr-4 py-2 border-l-4 ${active ? 'border-indigo-400 text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700' : 'border-transparent text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300'} text-base font-medium focus:outline-none transition duration-150 ease-in-out`
            }
            href={href}
        >
            {children}
        </InertiaLink>
    );
}

// stubs/inertia/resources/js/Components/ResponsiveNavLink.vue
<template>
    <div>
        <button :class="classes" class="w-full text-left" v-if="as == 'button'">
            <slot />
        </button>

        <inertia-link :href="href" :class="classes" v-else>
            <slot />
        </inertia-link>
    </div>
</template>

<script>
    export default {
        props: ['active', 'href', 'as'],

        computed: {
            classes() {
                return this.active
                            ? 'block pl-3 pr-4 py-2 border-l-4 border-indigo-400 text-base font-medium text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700 transition duration-150 ease-in-out'
                            : 'block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out'
            }
        }
    }
</script>
