// stubs/inertia-svelte/resources/js/Components/InputLabel.svelte
<script>
    export let value = undefined;
    let forInput;
    export { forInput as for };
</script>

<label for={forInput} class="block text-sm font-medium text-gray-700 dark:text-gray-300">
    {#if value}
        <span>{value}</span>
    {:else}
        <span><slot /></span>
    {/if}
</label>

// stubs/inertia-react-ts/resources/js/Components/InputLabel.tsx
import { LabelHTMLAttributes } from 'react';

export default function InputLabel({
    value,
    className = '',
    children,
    ...props
}: LabelHTMLAttributes<HTMLLabelElement> & { value?: string }) {
    return (
        <label
            {...props}
            className={
                `block text-sm font-medium text-gray-700 dark:text-gray-300 ` +
                className
            }
        >
            {value ?? children}
        </label>
    );
}
