// stubs/inertia-vue/resources/js/Components/ValidationErrors.vue
<template>
    <div v-if="hasErrors">
        <div class="font-medium text-red-600">Whoops! Something went wrong.</div>

        <ul class="mt-3 list-disc list-inside text-sm text-red-600">
            <li v-for="(error, key) in errors" :key="key">{{ error }}</li>
        </ul>
    </div>
</template>

<script>
    export default {
        computed: {
            errors() {
                return this.$page.props.errors
            },

            hasErrors() {
                return Object.keys(this.errors).length > 0
            },
        }
    }
</script>

// stubs/inertia-react/resources/js/Components/Forms/ValidationErrors.js
import React from "react";

export default function ValidationErros(props) {
    return (
        Object.keys(props.errors).length > 0 && (
            <div className="mb-4">
                <div className="font-medium text-red-600">
                    Whoops! Something went wrong.
                </div>
                <ul className="mt-3 list-disc list-inside text-sm text-red-600">
                    {Object.keys(props.errors).map(function (key, index) {
                        return <li key={index}>{props.errors[key]}</li>;
                    })}
                </ul>
            </div>
        )
    );
}
