// stubs/inertia-vue-ts/resources/js/Layouts/GuestLayout.vue
<script setup lang="ts">
import ApplicationLogo from '@/Components/ApplicationLogo.vue';
import { Link } from '@inertiajs/vue3';
</script>

<template>
    <div
        class="flex min-h-screen flex-col items-center bg-gray-100 pt-6 sm:justify-center sm:pt-0 dark:bg-gray-900"
    >
        <div>
            <Link href="/">
                <ApplicationLogo class="h-20 w-20 fill-current text-gray-500" />
            </Link>
        </div>

        <div
            class="mt-6 w-full overflow-hidden bg-white px-6 py-4 shadow-md sm:max-w-md sm:rounded-lg dark:bg-gray-800"
        >
            <slot />
        </div>
    </div>
</template>

// stubs/inertia-svelte/resources/js/Layouts/GuestLayout.svelte
<script>
    import ApplicationLogo from '@/Components/ApplicationLogo.svelte';
    import { Link } from '@inertiajs/svelte';
</script>

<div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100 dark:bg-gray-900">
    <div>
        <Link href="/">
            <ApplicationLogo class="w-20 h-20 fill-current text-gray-500" />
        </Link>
    </div>

    <div
        class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg"
    >
        <slot />
    </div>
</div>
